name: Linting

on:
  push:

jobs:
  linting-python:
    name: Lint Python
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install Dependencies
        shell: bash
        run: |
          pip install -r requirements.txt
          pip install black isort flake8

      # These will use the configs in setup.cfg
      - name: Run flake8
        if: always()
        shell: bash
        run: python -m flake8 prodigy tests

      - name: Run black
        if: always()
        shell: bash
        run: python -m black --check .

      - name: Run isort
        if: always()
        shell: bash
        run: python -m isort --check .
