name: Simple Python test

on: [pull_request, workflow_call]

env:
  PACKAGE: prodigy

jobs:
  test:
    name: Run tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: '3.8'
            os: ubuntu-latest
          - python-version: '3.9'
            os: ubuntu-latest
          - python-version: '3.10'
            os: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: pip install -r requirements.txt

      # This test workflow isn't the super picky and careful one we use
      # where we install from source etc. This one should fail on most
      # code bugs, and for now my problem is that I can't login to
      # Azure Pipelines to see the errors.
      - name: Run doc tests
        run: |
          textual run docs/examples/bg.py --screenshot 1
          textual run docs/examples/border-sides.py --screenshot 1
          textual run docs/examples/border-base.py --screenshot 1
          textual run docs/examples/margin.py --screenshot 1
          textual run docs/examples/margin-sides.py --screenshot 1
          textual run docs/examples/padding-sides.py --screenshot 1
          textual run docs/examples/text-alignment.py --screenshot 1
          textual run docs/examples/dock-demo-2.py --screenshot 1
          textual run docs/examples/dock-demo-1.py --screenshot 1
          textual run docs/examples/text-style.py --screenshot 1
          textual run docs/examples/padding.py --screenshot 1
          textual run docs/examples/text-color.py --screenshot 1
